# Generated by Django 4.1 on 2023-08-10 19:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bettor2', models.CharField(max_length=256)),
                ('bet_description', models.TextField()),
                ('bet_amount', models.PositiveIntegerField()),
                ('win_amount', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2023, 8, 10, 19, 33, 53, 698002, tzinfo=datetime.timezone.utc))),
                ('bettor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bettor1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
