# Generated by Django 4.1 on 2023-08-28 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0002_alter_bet_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bettor2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bettor2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bet',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
