# Generated by Django 4.1 on 2023-08-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_alter_bet_bettor2_alter_bet_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='bet_amount',
            new_name='bettor1risk',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='win_amount',
            new_name='bettor2risk',
        ),
    ]
