# Generated by Django 4.1 on 2023-08-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_rename_bet_amount_bet_bettor1risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bettor1risk',
            field=models.PositiveIntegerField(verbose_name='My Wager'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bettor2risk',
            field=models.PositiveIntegerField(verbose_name="Opponent's Wager"),
        ),
    ]
