# Generated by Django 4.1 on 2023-09-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_bet_loser_updatebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='settled_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='UpdateBalance',
        ),
    ]
